ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "1"
default_platform(:ios)

platform :ios do
  desc "Compila o aplicativo"
  lane :build do
    gym(
      scheme: "FuturoCafé",  # Certifique-se de que este é o esquema correto
      project: "ios/FuturoCafé.xcodeproj"  # Caminho correto do seu projeto
    )
  end

  desc "Testa o aplicativo"
  lane :test do
    scan(scheme: "FuturoCaféTests") # Certifique-se de que você tem testes configurados
  end

  desc "Distribui para o TestFlight"
  lane :beta do
    build
    upload_to_testflight
  end
end
