name: Build Pipeline

on:
  push:
    branches:
      - feature/futuro-cafe
  pull_request:
    branches:
      - feature/futuro-cafe

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Build the iOS app
        run: bundle exec fastlane gym --scheme "FuturoCafé" --export_method "ad-hoc"

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: FuturoCafé.ipa
          path: path/to/output/FuturoCafé.ipa  # Ajuste para o caminho correto do seu .ipa

  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Give execute permission to gradlew
        run: chmod +x android/gradlew

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the Android app
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: FuturoCafé.apk
          path: android/app/build/outputs/apk/release/app-release.apk  # Ajuste para o caminho correto do seu .apk
